table fato_gastos_mensais
	lineageTag: 2baced81-7d49-4fe8-970a-00fdbba94aae

	measure Total_Gastos_Mensais = SUM(fato_gastos_mensais[valor_total])
		formatString: R$ #,##0.00
		displayFolder: Gastos
		lineageTag: 7824690b-5644-4c17-b3ed-6d2b52a702a9

	measure Total_Imposto_Indireto_Embutido = SUM(fato_gastos_mensais[imposto_embutido])
		formatString: R$ #,##0.00
		displayFolder: Gastos
		lineageTag: 96a67a84-0a61-4469-a0c2-53223dae9cc0

	measure Total_Custo_Real = SUM(fato_gastos_mensais[custo_real])
		formatString: R$ #,##0.00
		displayFolder: Gastos
		lineageTag: 4a847fcd-1ec2-4436-b8d7-f3d87021bedc

	measure Aliq_Indireta_Efetiva_Pct = DIVIDE([Total_Imposto_Indireto_Embutido], [Total_Gastos_Mensais], 0) * 100
		formatString: 0.00"%"
		displayFolder: Gastos
		lineageTag: c0a9b65e-8d36-4153-acad-eb315ca305ba

	measure Imposto_Indireto_Federal = SUM(fato_gastos_mensais[imp_federal])
		formatString: R$ #,##0.00
		displayFolder: Gastos
		lineageTag: 8abc4fc1-363a-4c15-90b9-13acda61a707

	measure Imposto_Indireto_Estadual = SUM(fato_gastos_mensais[imp_estadual])
		formatString: R$ #,##0.00
		displayFolder: Gastos
		lineageTag: 5e0e8a53-c5bc-493d-b84e-d66133dc55cb

	measure Imposto_Indireto_Municipal = SUM(fato_gastos_mensais[imp_municipal])
		formatString: R$ #,##0.00
		displayFolder: Gastos
		lineageTag: fcb3c80b-1b47-4a28-b82d-8a2c0b111d92

	measure Imposto_Patrimonial_IPVA = 250
		formatString: R$ #,##0.00
		displayFolder: Patrimonial
		lineageTag: 4bb6b2fd-d1ef-45db-9f80-c7c1d86bbdce

	measure Imposto_Patrimonial_IPTU = 100
		formatString: R$ #,##0.00
		displayFolder: Patrimonial
		lineageTag: 99b6dde7-9de9-4453-b2a3-1d62e52dfe0f

	measure Imposto_Patrimonial_Licenciamento = 20
		formatString: R$ #,##0.00
		displayFolder: Patrimonial
		lineageTag: 7c6d50a8-c150-4ab8-a791-470e2d2257f6

	measure Total_Patrimonial = [Imposto_Patrimonial_IPVA] + [Imposto_Patrimonial_IPTU] + [Imposto_Patrimonial_Licenciamento]
		formatString: R$ #,##0.00
		displayFolder: Patrimonial
		lineageTag: a818530c-29ef-48ec-bedd-0d88e8ed9008

	measure Carga_Total_Tributos = [Tributacao_Direta_Total] + [Total_Imposto_Indireto_Embutido] + [Total_Patrimonial]
		formatString: R$ #,##0.00
		displayFolder: Carga Total
		lineageTag: dc24d0ce-e2c9-4617-838b-79a9e361a275

	measure Carga_Efetiva_Sobre_Renda_Bruta_Pct = DIVIDE([Carga_Total_Tributos], [Renda_Bruta_Total], 0) * 100
		formatString: 0.00"%"
		displayFolder: Carga Total
		lineageTag: 9f858c30-e912-4494-8989-25ef843d060a

	measure Pct_Carga_Direta = DIVIDE([Tributacao_Direta_Total], [Renda_Bruta_Total], 0) * 100
		formatString: 0.00"%"
		displayFolder: Carga Total
		lineageTag: 8e61be66-9251-4557-b55a-0af31472c877

	measure Pct_Carga_Indireta = DIVIDE([Total_Imposto_Indireto_Embutido], [Renda_Bruta_Total], 0) * 100
		formatString: 0.00"%"
		displayFolder: Carga Total
		lineageTag: 42e8150b-8b8c-4e00-be4a-ebba09b37f87

	measure Pct_Carga_Patrimon = DIVIDE([Total_Patrimonial], [Renda_Bruta_Total], 0) * 100
		formatString: 0.00"%"
		displayFolder: Carga Total
		lineageTag: 492fe047-0a27-4251-b85e-a7d4601eac0a

	measure Resultado_Final = [Renda_Liquida_Total] - [Total_Gastos_Mensais] - [Total_Patrimonial]
		formatString: R$ #,##0.00
		displayFolder: Resultado
		lineageTag: 5514a437-7290-4fcc-8e58-707c1e8d8272

	measure Comprometimento_Renda_Liquida_Pct = DIVIDE([Total_Gastos_Mensais] + [Total_Patrimonial], [Renda_Liquida_Total], 0) * 100
		formatString: 0.00"%"
		displayFolder: Resultado
		lineageTag: c20fe430-4708-438a-88c6-574d4e40b037

	measure Margem_Poupanca_Pct = DIVIDE([Resultado_Final], [Renda_Bruta_Total], 0) * 100
		formatString: 0.00"%"
		displayFolder: Resultado
		lineageTag: 4ddb083a-383c-403e-aed2-0489b00b79dd

	measure HTML_Ticker_Hero = "<style>*{margin:0;padding:0;box-sizing:border-box;font-family:Inter,system-ui,sans-serif}body{background:#0f0f1a;overflow:hidden;height:100%;display:flex;align-items:center}.tw{width:100%;overflow:hidden;background:rgba(231,76,60,0.10);border-top:1px solid rgba(231,76,60,0.45);padding:14px 0}.t{display:inline-block;white-space:nowrap;animation:tick 55s linear infinite}.t span{color:rgba(255,255,255,.82);font-size:13px;font-weight:500;padding:0 56px}.l{color:#e74c3c;font-weight:700;text-transform:uppercase;font-size:10px;letter-spacing:1.5px;margin-right:6px}@keyframes tick{0%{transform:translateX(90vw)}100%{transform:translateX(-100%)}}</style><div class=""tw""><div class=""t""><span><span class=""l"">Carga Total</span>" & FORMAT([Carga_Efetiva_Sobre_Renda_Bruta_Pct], "0.0") & "% da renda bruta</span><span><span class=""l"">Impostos/mes</span>R$ " & FORMAT([Carga_Total_Tributos], "#,##0") & "</span><span><span class=""l"">Deficit</span>-R$ " & FORMAT(ABS([Resultado_Final]), "#,##0") & " todo mes</span><span><span class=""l"">Posicao</span>Top 10% do Brasil - ainda no vermelho</span><span><span class=""l"">Cascata</span>ICMS incide sobre preco que ja inclui PIS COFINS e IPI</span><span><span class=""l"">Combustivel</span>43% do preco bomba e imposto</span><span><span class=""l"">Energia</span>44% da conta de luz e tributo</span><span><span class=""l"">Invisiveis</span>R$ 2.215/mes em impostos embutidos nas compras</span></div></div>"
		displayFolder: HTML Visuals
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567801

	measure HTML_KPIs_Hero = "<style>*{margin:0;padding:0;box-sizing:border-box;font-family:Inter,system-ui,sans-serif}body{background:transparent;height:100%;overflow:hidden}.wrap{display:flex;gap:14px;padding:12px;height:100%;align-items:stretch}.c{flex:1;background:rgba(255,255,255,0.04);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,0.07);border-radius:16px;padding:18px 22px;display:flex;flex-direction:column;justify-content:space-between;transition:all .25s;cursor:default}.c:hover{background:rgba(255,255,255,0.07);border-color:rgba(255,255,255,0.15);transform:translateY(-3px)}.ico{font-size:22px;margin-bottom:2px}.lbl{color:rgba(255,255,255,.4);font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:2px}.val{font-size:36px;font-weight:800;letter-spacing:-1.5px;line-height:1.05}.sub{color:rgba(255,255,255,.28);font-size:11px;margin-top:4px}.r{color:#e74c3c}.o{color:#e67e22}.b{color:#3498db}.pulse{animation:p 2.5s ease-in-out infinite}@keyframes p{0%,100%{opacity:1}50%{opacity:.5}}</style><div class=""wrap""><div class=""c""><div class=""ico"">Carga</div><div class=""lbl"">Carga Tributaria Efetiva</div><div class=""val r pulse"">" & FORMAT([Carga_Efetiva_Sobre_Renda_Bruta_Pct], "0.0") & "%</div><div class=""sub"">sobre a renda bruta familiar</div></div><div class=""c""><div class=""ico"">Impostos</div><div class=""lbl"">Total de Impostos/mes</div><div class=""val o"">R$ " & FORMAT([Carga_Total_Tributos], "#,##0") & "</div><div class=""sub"">diretos + indiretos + patrimoniais</div></div><div class=""c""><div class=""ico"">Deficit</div><div class=""lbl"">Resultado Mensal</div><div class=""val r"">-R$ " & FORMAT(ABS([Resultado_Final]), "#,##0") & "</div><div class=""sub"">deficit mesmo no Top 10% da renda</div></div><div class=""c""><div class=""ico"">Posicao</div><div class=""lbl"">Posicao no Brasil</div><div class=""val b"">" & [Percentil_Brasil_Estimado] & "</div><div class=""sub"">em renda - ainda no vermelho</div></div></div>"
		displayFolder: HTML Visuals
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678902

	measure HTML_Sankey_Hero =
			VAR _Q = UNICHAR(34)
			VAR _C = UNICHAR(44)
			VAR _L = CONCATENATEX(Fluxo_Sankey, "{" & _Q & "s" & _Q & ":" & _Q & Fluxo_Sankey[fonte] & _Q & _C & _Q & "t" & _Q & ":" & _Q & Fluxo_Sankey[destino] & _Q & _C & _Q & "v" & _Q & ":" & INT(Fluxo_Sankey[valor]) & _C & _Q & "tp" & _Q & ":" & _Q & Fluxo_Sankey[tipo] & _Q & "}", _C)
				VAR _h1 = "<!DOCTYPE html><html><head><meta charset=""UTF-8""><style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0f0f1a;overflow:hidden}#c{width:100%;height:100vh}path{transition:opacity .2s}path:hover{opacity:.7!important}</style></head><body><div id=c></div><script>"
				VAR _h2 = "const L=[" & _L & "];(function(){var CO={Direto:""#e74c3c"",Indireto:""#e67e22"",Patrimonial:""#9b59b6"",Gasto:""#3498db""};var NS=""http://www.w3.org/2000/svg"";function mk(tag,attrs){var e=document.createElementNS(NS,tag);Object.keys(attrs).forEach(function(k){e.setAttribute(k,attrs[k]);});return e;}var nm={};L.forEach(function(l){if(!nm[l.s])nm[l.s]={id:l.s,out:[],inl:[],col:-1};if(!nm[l.t])nm[l.t]={id:l.t,out:[],inl:[],col:-1};nm[l.s].out.push(l);nm[l.t].inl.push(l);});var ns=Object.values(nm);ns.filter(function(n){return n.inl.length===0;}).forEach(function(n){n.col=0;});for(var i=0;i<ns.length*2;i++){L.forEach(function(l){var s=nm[l.s],t=nm[l.t];if(s.col>=0&&t.col<=s.col)t.col=s.col+1;});}var maxC=Math.max.apply(null,ns.map(function(n){return n.col;}));ns.forEach(function(n){n.val=Math.max(n.out.reduce(function(s,l){return s+l.v;},0),n.inl.reduce(function(s,l){return s+l.v;},0));});var cv=document.getElementById(""c"");var W=cv.offsetWidth||800,H=cv.offsetHeight||440;var nw=14,pad=7,mx=24,mr=190;var cw=(W-mx-mr-nw)/(maxC||1);var tv=ns.filter(function(n){return n.inl.length===0;}).reduce(function(s,n){return s+n.val;},0);var sc=(H-40)/tv;var cols={};ns.forEach(function(n){if(!cols[n.col])cols[n.col]=[];cols[n.col].push(n);});Object.keys(cols).forEach(function(c){var cn=cols[c];cn.sort(function(a,b){return b.val-a.val;});var th=cn.reduce(function(s,n){return s+n.val*sc;},0)+pad*(cn.length-1);var y=Math.max((H-th)/2,5);cn.forEach(function(n){n.x=mx+c*cw;n.y=y;n.h=Math.max(n.val*sc,2);y+=n.h+pad;});});var so={},to={};ns.forEach(function(n){so[n.id]=n.y;to[n.id]=n.y;});var svg=mk(""svg"",{width:W,height:H});svg.style.display=""block"";"
				VAR _h3 = "L.forEach(function(l){var s=nm[l.s],t=nm[l.t],lh=Math.max(l.v*sc,1.5);var sy=so[l.s],ty=to[l.t];so[l.s]+=lh;to[l.t]+=lh;var x1=s.x+nw,x2=t.x,cx=(x1+x2)/2;var d=""M""+x1+"",""+sy+""C""+cx+"",""+sy+"" ""+cx+"",""+ty+"" ""+x2+"",""+ty+""L""+x2+"",""+(ty+lh)+""C""+cx+"",""+(ty+lh)+"" ""+cx+"",""+(sy+lh)+"" ""+x1+"",""+(sy+lh)+""Z"";var p=mk(""path"",{d:d,fill:CO[l.tp]||""#27ae60"",opacity:""0.35""});var ti=document.createElementNS(NS,""title"");ti.textContent=l.s+"" -> ""+l.t+"": R$ ""+Math.round(l.v).toLocaleString(""pt-BR"");p.appendChild(ti);svg.appendChild(p);});ns.forEach(function(n){var col;if(n.inl.length===0)col=""#27ae60"";else if(n.out.length>0)col=CO[n.out[0].tp]||""#27ae60"";else col=CO[n.inl[0].tp]||""#27ae60"";svg.appendChild(mk(""rect"",{x:n.x,y:n.y,width:nw,height:Math.max(n.h,2),fill:col,rx:2,opacity:""0.9""}));var lx=n.col<maxC?n.x+nw+5:n.x-5;var ta=n.col<maxC?""start"":""end"";var lb=n.id+(n.val>=50?"" R$""+Math.round(n.val).toLocaleString(""pt-BR""):"""");var txt=mk(""text"",{x:lx,y:n.y+n.h/2,dy:""0.35em""});txt.setAttribute(""text-anchor"",ta);txt.setAttribute(""font-size"",""10"");txt.setAttribute(""font-family"",""Inter,system-ui,sans-serif"");txt.setAttribute(""fill"",""rgba(255,255,255,.78)"");txt.setAttribute(""font-weight"",""500"");txt.textContent=lb;svg.appendChild(txt);});cv.appendChild(svg);})();</script></body></html>"
				RETURN _h1 & _h2 & _h3
		displayFolder: HTML Visuals
		lineageTag: c3d4e5f6-a7b8-9012-cdef-012345678903


	measure HTML_Tributacao_Hero =
				VAR _dir  = ROUND([Tributacao_Direta_Total], 0)
				VAR _ind  = ROUND([Total_Imposto_Indireto_Embutido], 0)
				VAR _pat  = ROUND([Total_Patrimonial], 0)
				VAR _tot  = _dir + _ind + _pat
				VAR _ren  = ROUND([Renda_Bruta_Total], 0)
				VAR _inss = ROUND([INSS_Total_Familia], 0)
				VAR _irpf = ROUND([IRPF_Total_Familia], 0)
				VAR _fed  = ROUND([Imposto_Indireto_Federal], 0)
				VAR _est  = ROUND([Imposto_Indireto_Estadual], 0)
				VAR _mun  = ROUND([Imposto_Indireto_Municipal], 0)
				VAR _pD   = FORMAT(DIVIDE(_dir,_ren,0)*100,"0.0")
				VAR _pI   = FORMAT(DIVIDE(_ind,_ren,0)*100,"0.0")
				VAR _pP   = FORMAT(DIVIDE(_pat,_ren,0)*100,"0.0")
				VAR _pT   = FORMAT(DIVIDE(_tot,_ren,0)*100,"0.0")
				VAR _s1   = FORMAT(DIVIDE(_dir,_tot,0)*100,"0.0")
				VAR _s2   = FORMAT(DIVIDE(_dir+_ind,_tot,0)*100,"0.0")
				VAR _bFd  = FORMAT(DIVIDE(_fed,_ind,0)*100,"0")
				VAR _bEt  = FORMAT(DIVIDE(_est,_ind,0)*100,"0")
				VAR _bMn  = FORMAT(DIVIDE(_mun,_ind,0)*100,"0")
				VAR _bIn  = FORMAT(DIVIDE(_inss,_dir,0)*100,"0")
				VAR _bIr  = FORMAT(DIVIDE(_irpf,_dir,0)*100,"0")
				VAR _fDir = FORMAT(_dir,"#,##0")
				VAR _fInd = FORMAT(_ind,"#,##0")
				VAR _fPat = FORMAT(_pat,"#,##0")
				VAR _fIns = FORMAT(_inss,"#,##0")
				VAR _fIrp = FORMAT(_irpf,"#,##0")
				VAR _fFed = FORMAT(_fed,"#,##0")
				VAR _fEst = FORMAT(_est,"#,##0")
				VAR _fMun = FORMAT(_mun,"#,##0")
				VAR _grad = "conic-gradient(#e74c3c 0% " & _s1 & "%,#e67e22 " & _s1 & "% " & _s2 & "%,#9b59b6 " & _s2 & "% 100%)"
				VAR _h1 = "<!DOCTYPE html><html><head><meta charset=""UTF-8""><style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0f0f1a;font-family:Inter,system-ui,sans-serif;color:#fff;height:100vh;display:flex;flex-direction:column;padding:16px;gap:10px}.top{display:flex;gap:10px;flex-shrink:0}.card{flex:1;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:12px 16px}.lbl{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:2px;color:rgba(255,255,255,.35);margin-bottom:4px}.val{font-size:24px;font-weight:800;letter-spacing:-1px;line-height:1.1}.sub{font-size:10px;color:rgba(255,255,255,.3);margin-top:3px}.mid{display:flex;gap:16px;flex:1;min-height:0}.dc{flex:0 0 200px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px}.dn{width:168px;height:168px;border-radius:50%;position:relative}.hl{position:absolute;inset:22px;border-radius:50%;background:#0f0f1a;display:flex;flex-direction:column;align-items:center;justify-content:center}.hp{font-size:21px;font-weight:800}.hq{font-size:9px;color:rgba(255,255,255,.38);text-transform:uppercase;letter-spacing:1px}.leg{width:100%;display:flex;flex-direction:column;gap:5px}.lr{display:flex;align-items:center;gap:7px;font-size:11px}.ld{width:9px;height:9px;border-radius:2px;flex-shrink:0}.ln{flex:1;color:rgba(255,255,255,.55)}.lv{font-weight:700}.bc{flex:1;display:flex;flex-direction:column;justify-content:center;gap:8px}.sh{font-size:9px;color:rgba(255,255,255,.3);text-transform:uppercase;letter-spacing:2px;font-weight:600;margin-bottom:1px;margin-top:6px}.br .bh{display:flex;justify-content:space-between;font-size:11px;margin-bottom:3px}.bn{color:rgba(255,255,255,.5)}.bv{font-weight:600}.bt{height:6px;background:rgba(255,255,255,.07);border-radius:3px;overflow:hidden}.bf{height:100%;border-radius:3px}</style></head><body><div class=""top""><div class=""card""><div class=""lbl"">Tributacao Direta</div><div class=""val"" style=""color:#e74c3c"">R$ " & _fDir & "</div><div class=""sub"">INSS R$" & _fIns & " + IRPF R$" & _fIrp & " &middot; " & _pD & "% da renda</div></div>"
				      & "<div class=""card""><div class=""lbl"">Tributacao Indireta</div><div class=""val"" style=""color:#e67e22"">R$ " & _fInd & "</div><div class=""sub"">embutida nos precos &middot; " & _pI & "% da renda</div></div>"
				      & "<div class=""card""><div class=""lbl"">Patrimonial</div><div class=""val"" style=""color:#9b59b6"">R$ " & _fPat & "</div><div class=""sub"">IPVA + IPTU + Licenc. &middot; " & _pP & "% da renda</div></div></div>"
				VAR _h2 = "<div class=""mid""><div class=""dc""><div class=""dn"" style=""background:" & _grad & """><div class=""hl""><span class=""hp"">" & _pT & "%</span><span class=""hq"">da renda</span></div></div>"
				      & "<div class=""leg""><div class=""lr""><div class=""ld"" style=""background:#e74c3c""></div><span class=""ln"">Direta</span><span class=""lv"">" & _pD & "%</span></div><div class=""lr""><div class=""ld"" style=""background:#e67e22""></div><span class=""ln"">Indireta</span><span class=""lv"">" & _pI & "%</span></div><div class=""lr""><div class=""ld"" style=""background:#9b59b6""></div><span class=""ln"">Patrimonial</span><span class=""lv"">" & _pP & "%</span></div></div></div>"
				VAR _h3 = "<div class=""bc""><div class=""sh"">Indireta por esfera governamental</div><div class=""br""><div class=""bh""><span class=""bn"">Federal (PIS/COFINS/IPI)</span><span class=""bv"">R$ " & _fFed & "</span></div><div class=""bt""><div class=""bf"" style=""background:#3498db;width:" & _bFd & "%""></div></div></div>"
				      & "<div class=""br""><div class=""bh""><span class=""bn"">Estadual (ICMS)</span><span class=""bv"">R$ " & _fEst & "</span></div><div class=""bt""><div class=""bf"" style=""background:#27ae60;width:" & _bEt & "%""></div></div></div>"
				      & "<div class=""br""><div class=""bh""><span class=""bn"">Municipal (ISS)</span><span class=""bv"">R$ " & _fMun & "</span></div><div class=""bt""><div class=""bf"" style=""background:#f39c12;width:" & _bMn & "%""></div></div></div>"
				      & "<div class=""sh"">Direta: INSS vs IRPF</div><div class=""br""><div class=""bh""><span class=""bn"">INSS - Previdencia Social</span><span class=""bv"">R$ " & _fIns & "</span></div><div class=""bt""><div class=""bf"" style=""background:#e74c3c;width:" & _bIn & "%""></div></div></div>"
				      & "<div class=""br""><div class=""bh""><span class=""bn"">IRPF - Imposto de Renda</span><span class=""bv"">R$ " & _fIrp & "</span></div><div class=""bt""><div class=""bf"" style=""background:#e67e22;width:" & _bIr & "%""></div></div></div></div></div></body></html>"
				RETURN _h1 & _h2 & _h3
		displayFolder: HTML Visuals
		lineageTag: d4e5f6a7-b8c9-0123-defa-123456789004

	column id
		dataType: int64
		formatString: 0
		lineageTag: ac5d674d-a7cc-4e6f-9e38-41ac41e9b096
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column imp_estadual
		dataType: int64
		formatString: 0
		lineageTag: f2f8eee5-bb2e-4239-8b52-cedd626e0243
		summarizeBy: sum
		sourceColumn: imp_estadual

		annotation SummarizationSetBy = Automatic

	column imp_municipal
		dataType: int64
		formatString: 0
		lineageTag: 9b7f03a3-467f-43ec-92ab-2607d27b7e22
		summarizeBy: sum
		sourceColumn: imp_municipal

		annotation SummarizationSetBy = Automatic

	column etapa_cadeia_principal
		dataType: string
		lineageTag: 27e9fc7f-6049-4c41-9361-6ac29c5bfac8
		summarizeBy: none
		sourceColumn: etapa_cadeia_principal

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: 33f3d012-af1f-436e-94e3-52ba76a04b68
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column grupo
		dataType: string
		lineageTag: db95482c-b7d4-4700-aafa-0ca49bdf2f5d
		summarizeBy: none
		sourceColumn: grupo

		annotation SummarizationSetBy = Automatic

	column tipo_gasto
		dataType: string
		lineageTag: 5173b70c-fb02-4d90-93ba-b3456c9b9916
		summarizeBy: none
		sourceColumn: tipo_gasto

		annotation SummarizationSetBy = Automatic

	column valor_total
		dataType: int64
		formatString: 0
		lineageTag: 9d814e7f-6b35-484f-bc51-d9156baab27b
		summarizeBy: sum
		sourceColumn: valor_total

		annotation SummarizationSetBy = Automatic

	column aliq_indireta_pct
		dataType: int64
		formatString: 0
		lineageTag: eb4ad051-f844-4dff-a44f-2e305978bf21
		summarizeBy: sum
		sourceColumn: aliq_indireta_pct

		annotation SummarizationSetBy = Automatic

	column imposto_embutido
		dataType: int64
		formatString: 0
		lineageTag: 0742bb55-1604-4189-a3d3-993c5c5d4620
		summarizeBy: sum
		sourceColumn: imposto_embutido

		annotation SummarizationSetBy = Automatic

	column custo_real
		dataType: int64
		formatString: 0
		lineageTag: 2699c997-94fc-4e3d-8a2b-960c988b86f5
		summarizeBy: sum
		sourceColumn: custo_real

		annotation SummarizationSetBy = Automatic

	column imp_federal
		dataType: int64
		formatString: 0
		lineageTag: c2747591-6fd9-4fca-90ea-2cc62558a9ab
		summarizeBy: sum
		sourceColumn: imp_federal

		annotation SummarizationSetBy = Automatic

	partition fato_gastos_mensais = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("C:\PROJETOS\PROJETO_IMPOSTOS\dados"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each [Name] = "fato_gastos_mensais.csv"),
				    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Filtradas", "Conteudo", each Csv.Document([Content])),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Personalização Adicionada",{"Conteudo"}),
				    #"Conteudo Expandido" = Table.ExpandTableColumn(#"Outras Colunas Removidas", "Conteudo", {"Column1", "Column10", "Column11", "Column12", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9"}, {"Column1", "Column10", "Column11", "Column12", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9"}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Conteudo Expandido", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"id", Int64.Type}, {"imp_estadual", Int64.Type}, {"imp_municipal", Int64.Type}, {"etapa_cadeia_principal", type text}, {"categoria", type text}, {"grupo", type text}, {"tipo_gasto", type text}, {"valor_total", Int64.Type}, {"aliq_indireta_pct", Int64.Type}, {"imposto_embutido", Int64.Type}, {"custo_real", Int64.Type}, {"imp_federal", Int64.Type}}, "en-US")
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

